server:
  port: 7081
  servlet:
    context-path: /demo

spring:
  rabbitmq:
    addresses: 172.1.9.16
    port: 5672
    username: trimps
    password: bishenglu

  application:
    name: websocket


  freemarker:
    request-context-attribute: request


  jpa:
    database-platform: com.enigmabridge.hibernate.dialect.SQLiteDialect #自己配置的方言
    hibernate:
      ddl-auto: none
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:db/myDb
    username: root
    password: root
