server:
  port: 7081
  servlet:
    context-path: /demo

spring:
  rabbitmq:
    addresses: 172.1.9.16
    port: 5672
    username: root
    password: root

  application:
    name: websocket


  freemarker:
    request-context-attribute: request



